/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Full size.
   */
  static readonly FULL_SIZE: string = '100%';

  /**
   * List item width.
   */
  static readonly LIST_ITEM_WIDTH: string = '25%';

  /**
   * List width.
   */
  static readonly LIST_WIDTH: string = '60%';

  /**
   * Column width.
   */
  static readonly COLUMN_WIDTH: string = '60%';

  /**
   * Video information width.
   */
  static readonly VIDEO_INFO_WIDTH: string = '80%';

  /**
   * Text width.
   */
  static readonly TEXT_WIDTH: string = '70%';

  /**
   * Column height.
   */
  static readonly COLUMN_HEIGHT: string = '70%';

  /**
   * Row width.
   */
  static readonly ROW_WIDTH: string = '66%';

  /**
   * Duration
   */
  static readonly DURATION: number = 200;
}